"""Tests for src/temporal/digest.py.

These tests verify the digest rendering system for daily, weekly, and
per-module changelog outputs in multiple formats.
"""

import json
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from unittest import mock

import pytest

from src.temporal.digest import (
    render_daily,
    render_module,
    render_weekly,
)
from src.temporal.store import TemporalStore


# ── Fixtures ──────────────────────────────────────────────────────

@pytest.fixture()
def store_with_commits(tmp_path):
    """Return a TemporalStore with enriched commits for testing."""
    db_path = tmp_path / "commits.sqlite"
    store = TemporalStore(db_path)

    # Insert sample commits across different intents and dates
    sample_data = [
        {
            "sha": "a" * 40,
            "author": "Alice",
            "date": "2026-05-08T10:00:00+02:00",
            "subject": "feat(auth): Add SSO support",
            "body": "Implemented SAML 2.0 SSO.",
            "files_json": json.dumps([{"path": "src/auth/sso.py", "status": "A", "insertions": 150, "deletions": 0}]),
            "intent": "feature",
            "summary": "Added SAML 2.0 SSO support for external users.",
            "modules_affected_json": json.dumps(["src/auth"]),
            "risk_score": 0.6,
            "enriched_at": "2026-05-08T11:00:00+00:00",
            "g_version": "1.0.0",
        },
        {
            "sha": "b" * 40,
            "author": "Bob",
            "date": "2026-05-08T14:00:00+02:00",
            "subject": "fix(api): Handle null response",
            "body": "Fixed NPE in API handler.",
            "files_json": json.dumps([{"path": "src/api/handler.py", "status": "M", "insertions": 5, "deletions": 2}]),
            "intent": "fix",
            "summary": "Fixed null pointer exception in API response handler.",
            "modules_affected_json": json.dumps(["src/api"]),
            "risk_score": 0.3,
            "enriched_at": "2026-05-08T15:00:00+00:00",
            "g_version": "1.0.0",
        },
        {
            "sha": "c" * 40,
            "author": "Alice",
            "date": "2026-05-07T09:00:00+02:00",
            "subject": "docs(readme): Update contributing guide",
            "body": "",
            "files_json": json.dumps([{"path": "README.md", "status": "M", "insertions": 20, "deletions": 5}]),
            "intent": "docs",
            "summary": "Updated the contributing guide with new steps.",
            "modules_affected_json": json.dumps(["."]),
            "risk_score": 0.1,
            "enriched_at": "2026-05-07T10:00:00+00:00",
            "g_version": "1.0.0",
        },
        {
            "sha": "d" * 40,
            "author": "Charlie",
            "date": "2026-05-01T10:00:00+02:00",
            "subject": "feat(billing): Add invoice export",
            "body": "CSV and PDF export for invoices.",
            "files_json": json.dumps([
                {"path": "src/billing/export.py", "status": "A", "insertions": 200, "deletions": 0},
                {"path": "tests/test_export.py", "status": "A", "insertions": 100, "deletions": 0},
            ]),
            "intent": "feature",
            "summary": "Added CSV and PDF invoice export functionality.",
            "modules_affected_json": json.dumps(["src/billing"]),
            "risk_score": 0.7,
            "enriched_at": "2026-05-01T11:00:00+00:00",
            "g_version": "1.0.0",
        },
    ]

    for data in sample_data:
        store.connection.execute("""
            INSERT OR REPLACE INTO commits (
                sha, author, date, subject, body, files_json,
                intent, summary, modules_affected_json, risk_score,
                enriched_at, g_version
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            data["sha"], data["author"], data["date"], data["subject"],
            data["body"], data["files_json"], data["intent"], data["summary"],
            data["modules_affected_json"], data["risk_score"],
            data["enriched_at"], data["g_version"],
        ))

    return store


# ── render_daily ──────────────────────────────────────────────────

class TestRenderDaily:
    def test_markdown_with_commits(self, store_with_commits):
        """Daily markdown with commits contains expected sections."""
        result = render_daily(store_with_commits, date(2026, 5, 8), fmt="markdown")
        assert "# Changelog — 2026-05-08" in result
        assert "2 commits" in result
        assert "## Features" in result
        assert "## Fixes" in result
        assert "high-risk" in result
        assert "Generated by Heliograph temporal digest" in result

    def test_markdown_empty_day(self, store_with_commits):
        """Daily markdown for a day with no commits returns empty message."""
        result = render_daily(store_with_commits, date(2026, 1, 1), fmt="markdown")
        assert "# Changelog — 2026-01-01" in result
        assert "No commits." in result

    def test_html_with_commits(self, store_with_commits):
        """Daily HTML contains expected structure."""
        result = render_daily(store_with_commits, date(2026, 5, 8), fmt="html")
        assert "<!DOCTYPE html>" in result
        assert "Changelog — 2026-05-08" in result
        assert "2 commits" in result
        assert "high-risk" in result

    def test_json_with_commits(self, store_with_commits):
        """Daily JSON is valid and contains expected fields."""
        result = render_daily(store_with_commits, date(2026, 5, 8), fmt="json")
        data = json.loads(result)
        assert data["date"] == "2026-05-08"
        assert data["total_commits"] == 2
        assert "feature" in str(data["by_intent"]).lower() or "Features" in str(data["by_intent"])
        assert len(data["commits"]) == 2

    def test_json_empty_day(self, store_with_commits):
        """Daily JSON for empty day."""
        result = render_daily(store_with_commits, date(2026, 1, 1), fmt="json")
        data = json.loads(result)
        assert data["total_commits"] == 0

    def test_slack_blocks_with_commits(self, store_with_commits):
        """Daily Slack blocks is valid JSON with blocks."""
        result = render_daily(store_with_commits, date(2026, 5, 8), fmt="slack_blocks")
        data = json.loads(result)
        assert "blocks" in data
        assert len(data["blocks"]) > 0
        # First block should be a header
        assert data["blocks"][0]["type"] == "header"

    def test_slack_empty_day(self, store_with_commits):
        """Daily Slack for empty day."""
        result = render_daily(store_with_commits, date(2026, 1, 1), fmt="slack_blocks")
        data = json.loads(result)
        assert "blocks" in data

    def test_unknown_format_raises(self, store_with_commits):
        """Unknown format raises ValueError."""
        with pytest.raises(ValueError, match="Unknown format"):
            render_daily(store_with_commits, date(2026, 5, 8), fmt="xml")

    def test_high_risk_detected(self, store_with_commits):
        """High-risk commits are flagged in markdown."""
        result = render_daily(store_with_commits, date(2026, 5, 8), fmt="markdown")
        # The SSO commit has risk_score=0.6
        assert "high-risk" in result


# ── render_weekly ─────────────────────────────────────────────────

class TestRenderWeekly:
    def test_weekly_monday(self, store_with_commits):
        """Weekly digest for Monday includes the week's commits."""
        # May 8, 2026 is a Friday. Monday of that week is May 4.
        result = render_weekly(store_with_commits, date(2026, 5, 4), fmt="markdown")
        # Should contain the May 1 commit (billing feature)
        assert "Changelog" in result
        assert "invoice" in result.lower() or "billing" in result.lower()

    def test_weekly_empty(self, store_with_commits):
        """Weekly digest for a week with no commits."""
        result = render_weekly(store_with_commits, date(2026, 1, 5), fmt="markdown")
        assert "No commits" in result


# ── render_module ─────────────────────────────────────────────────

class TestRenderModule:
    def test_module_auth(self, store_with_commits):
        """Module digest for src/auth returns the SSO commit."""
        result = render_module(store_with_commits, "src/auth", days=7, fmt="markdown")
        assert "Changelog" in result
        assert "SSO" in result

    def test_module_not_found(self, store_with_commits):
        """Module digest for non-existent module returns empty."""
        result = render_module(store_with_commits, "src/nonexistent", days=7, fmt="markdown")
        assert "No commits" in result

    def test_module_json(self, store_with_commits):
        """Module digest in JSON format."""
        result = render_module(store_with_commits, "src/auth", days=7, fmt="json")
        data = json.loads(result)
        assert "module" in data

    def test_module_html(self, store_with_commits):
        """Module digest in HTML format."""
        result = render_module(store_with_commits, "src/auth", days=7, fmt="html")
        assert "<!DOCTYPE html>" in result or "<html>" in result

    def test_module_slack(self, store_with_commits):
        """Module digest in Slack format."""
        result = render_module(store_with_commits, "src/auth", days=7, fmt="slack_blocks")
        data = json.loads(result)
        assert "blocks" in data


# ── Edge Cases ────────────────────────────────────────────────────

class TestEdgeCases:
    def test_single_commit(self, tmp_path):
        """Digest with exactly one commit."""
        db_path = tmp_path / "commits.sqlite"
        store = TemporalStore(db_path)
        store.connection.execute("""
            INSERT INTO commits (sha, author, date, subject, body, files_json,
                intent, summary, modules_affected_json, risk_score,
                enriched_at, g_version)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            "e" * 40, "Dave", "2026-05-08T10:00:00+02:00",
            "chore: Update dependencies", "",
            json.dumps([{"path": "requirements.txt", "status": "M", "insertions": 3, "deletions": 3}]),
            "chore", "Updated dependencies.",
            json.dumps(["."]), 0.1,
            "2026-05-08T11:00:00+00:00", "1.0.0",
        ))
        result = render_daily(store, date(2026, 5, 8), fmt="markdown")
        assert "1 commit" in result

    def test_commit_with_insufficient_evidence(self, tmp_path):
        """Digest handles abstain summaries gracefully."""
        db_path = tmp_path / "commits.sqlite"
        store = TemporalStore(db_path)
        store.connection.execute("""
            INSERT INTO commits (sha, author, date, subject, body, files_json,
                intent, summary, modules_affected_json, risk_score,
                enriched_at, g_version)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            "f" * 40, "Eve", "2026-05-08T10:00:00+02:00",
            "unknown: mysterious change", "",
            json.dumps([{"path": "src/weird.py", "status": "M", "insertions": 1, "deletions": 0}]),
            "unknown", "[INSUFFICIENT_EVIDENCE]",
            json.dumps(["src"]), 0.2,
            "2026-05-08T11:00:00+00:00", "1.0.0",
        ))
        result = render_daily(store, date(2026, 5, 8), fmt="markdown")
        assert "Changelog" in result
        assert "mysterious" in result
