"""Tests for src/temporal/channels/__init__.py.

These tests verify the pluggable delivery channel system for changelog digests.
"""

import json
import os
import tempfile
from pathlib import Path
from unittest import mock

import pytest

from src.temporal.channels import (
    CHANNEL_REGISTRY,
    Channel,
    EmailChannel,
    FileChannel,
    SlackChannel,
    load_channels,
    register,
)


# ── Fixtures ──────────────────────────────────────────────────────

SAMPLE_CONTENT = """# Changelog — 2026-05-08

**3 commits** by 2 authors.

## Features (1)
- `feat`: Add SSO support → (`abc1234`)

---
*Generated by Heliograph temporal digest.*
"""

SAMPLE_META = {"date": "2026-05-08"}


# ── Channel Registry ──────────────────────────────────────────────

class TestChannelRegistry:
    def test_built_in_channels_registered(self):
        """Built-in channels are registered."""
        assert "file" in CHANNEL_REGISTRY
        assert "slack" in CHANNEL_REGISTRY
        assert "email" in CHANNEL_REGISTRY

    def test_custom_channel_registration(self):
        """Custom channels can be registered via decorator."""
        @register("test_custom")
        class TestCustomChannel(Channel):
            name = "test_custom"

            def send(self, content, *, fmt="markdown", meta=None):
                pass

        assert "test_custom" in CHANNEL_REGISTRY
        assert CHANNEL_REGISTRY["test_custom"] is TestCustomChannel


# ── load_channels ─────────────────────────────────────────────────

class TestLoadChannels:
    def test_load_file_channel(self):
        """File channel loads from config."""
        config = {
            "temporal": {
                "delivery": [
                    {"type": "file", "path": "context/changelog/{date}.md"},
                ]
            }
        }
        channels = load_channels(config)
        assert len(channels) == 1
        assert isinstance(channels[0], FileChannel)

    def test_load_slack_channel(self):
        """Slack channel loads from config."""
        config = {
            "temporal": {
                "delivery": [
                    {"type": "slack", "webhook_url_env": "SLACK_WEBHOOK_URL", "channel": "#test"},
                ]
            }
        }
        channels = load_channels(config)
        assert len(channels) == 1
        assert isinstance(channels[0], SlackChannel)

    def test_load_email_channel(self):
        """Email channel loads from config."""
        config = {
            "temporal": {
                "delivery": [
                    {
                        "type": "email",
                        "smtp_host_env": "SMTP_HOST",
                        "from_addr": "test@example.com",
                        "to": ["dev@example.com"],
                    }
                ]
            }
        }
        channels = load_channels(config)
        assert len(channels) == 1
        assert isinstance(channels[0], EmailChannel)

    def test_load_multiple_channels(self):
        """Multiple channels load correctly."""
        config = {
            "temporal": {
                "delivery": [
                    {"type": "file", "path": "context/changelog/{date}.md"},
                    {"type": "slack", "webhook_url_env": "SLACK_WEBHOOK_URL"},
                ]
            }
        }
        channels = load_channels(config)
        assert len(channels) == 2
        assert isinstance(channels[0], FileChannel)
        assert isinstance(channels[1], SlackChannel)

    def test_unknown_channel_type_logged(self, caplog):
        """Unknown channel type is logged as warning."""
        config = {
            "temporal": {
                "delivery": [
                    {"type": "nonexistent"},
                ]
            }
        }
        channels = load_channels(config)
        assert len(channels) == 0

    def test_empty_delivery(self):
        """Empty delivery config returns empty list."""
        config = {"temporal": {"delivery": []}}
        channels = load_channels(config)
        assert channels == []

    def test_missing_delivery_section(self):
        """Missing delivery section returns empty list."""
        config = {}
        channels = load_channels(config)
        assert channels == []


# ── FileChannel ───────────────────────────────────────────────────

class TestFileChannel:
    def test_write_to_file(self, tmp_path):
        """FileChannel writes content to the specified path."""
        channel = FileChannel(path=str(tmp_path / "changelog" / "{date}.md"))
        meta = {"date": "2026-05-08"}
        channel.send(SAMPLE_CONTENT, meta=meta)

        expected = tmp_path / "changelog" / "2026-05-08.md"
        assert expected.exists()
        assert expected.read_text(encoding="utf-8") == SAMPLE_CONTENT

    def test_template_with_year_month_day(self, tmp_path):
        """Template variables are resolved correctly."""
        channel = FileChannel(path=str(tmp_path / "{year}" / "{month}" / "{day}.md"))
        meta = {"date": "2026-05-08", "year": "2026", "month": "05", "day": "08"}
        channel.send(SAMPLE_CONTENT, meta=meta)

        expected = tmp_path / "2026" / "05" / "08.md"
        assert expected.exists()

    def test_creates_parent_directories(self, tmp_path):
        """Parent directories are created if they don't exist."""
        channel = FileChannel(path=str(tmp_path / "a" / "b" / "c" / "output.md"))
        channel.send(SAMPLE_CONTENT, meta={})
        assert (tmp_path / "a" / "b" / "c" / "output.md").exists()


# ── SlackChannel ──────────────────────────────────────────────────

class TestSlackChannel:
    def test_missing_env_var(self):
        """Missing env var logs error and returns."""
        # Ensure the env var is NOT set
        env_key = "NONEXISTENT_WEBHOOK_URL"
        if env_key in os.environ:
            del os.environ[env_key]

        channel = SlackChannel(webhook_url_env=env_key)
        channel.send("{}", meta={})  # Should not crash

    @mock.patch("urllib.request.urlopen")
    @mock.patch("urllib.request.Request")
    def test_send_slack_blocks(self, mock_request, mock_urlopen, tmp_path):
        """SlackChannel sends slack_blocks format."""
        # Set the env var
        os.environ["TEST_WEBHOOK"] = "https://hooks.slack.com/test"
        try:
            channel = SlackChannel(webhook_url_env="TEST_WEBHOOK", channel="#test")
            payload = json.dumps({"blocks": [{"type": "header", "text": {"type": "plain_text", "text": "Test"}}]})

            mock_resp = mock.MagicMock()
            mock_resp.status = 200
            mock_urlopen.return_value = mock_resp
            mock_resp.__enter__ = mock.MagicMock(return_value=mock_resp)
            mock_resp.__exit__ = mock.MagicMock(return_value=False)

            channel.send(payload, fmt="slack_blocks", meta={})

            mock_request.assert_called_once()
            call_args = mock_request.call_args
            assert call_args[0][0] == "https://hooks.slack.com/test"
        finally:
            os.environ.pop("TEST_WEBHOOK", None)

    def test_dry_run_prints_payload(self):
        """Dry-run mode would print the JSON payload (tested via mock)."""
        os.environ["TEST_WEBHOOK"] = "https://hooks.slack.com/test"
        try:
            channel = SlackChannel(webhook_url_env="TEST_WEBHOOK")
            with mock.patch("urllib.request.urlopen") as mock_urlopen:
                mock_resp = mock.MagicMock()
                mock_resp.status = 200
                mock_urlopen.return_value = mock_resp
                mock_resp.__enter__ = mock.MagicMock(return_value=mock_resp)
                mock_resp.__exit__ = mock.MagicMock(return_value=False)

                channel.send('{"blocks": []}', fmt="slack_blocks")
                # If we get here without exception, the test passes
        finally:
            os.environ.pop("TEST_WEBHOOK", None)


# ── EmailChannel ──────────────────────────────────────────────────

class TestEmailChannel:
    def test_no_recipients(self):
        """EmailChannel with no recipients logs warning."""
        channel = EmailChannel(smtp_host_env="SMTP_HOST", to=[])
        # Should not send, but should not crash
        channel.send(SAMPLE_CONTENT, meta={"date": "2026-05-08"})

    def test_smtp_connection_failed(self):
        """EmailChannel handles SMTP failure gracefully."""
        channel = EmailChannel(
            smtp_host_env="SMTP_HOST",
            smtp_port_env="SMTP_PORT",
            from_addr="test@example.com",
            to=["dev@example.com"],
        )
        # Set env vars
        os.environ["SMTP_HOST"] = "localhost"
        os.environ["SMTP_PORT"] = "25"
        try:
            # This will fail to connect, but should not crash
            channel.send(SAMPLE_CONTENT, meta={"date": "2026-05-08"})
        except Exception:
            pass  # Expected to fail on localhost
        finally:
            os.environ.pop("SMTP_HOST", None)
            os.environ.pop("SMTP_PORT", None)

    @mock.patch("smtplib.SMTP")
    def test_send_success(self, mock_smtp):
        """EmailChannel sends successfully."""
        mock_server = mock.MagicMock()
        mock_smtp.return_value = mock_server

        channel = EmailChannel(
            smtp_host_env="SMTP_HOST",
            smtp_port_env="SMTP_PORT",
            from_addr="test@example.com",
            to=["dev@example.com"],
        )
        os.environ["SMTP_HOST"] = "smtp.example.com"
        os.environ["SMTP_PORT"] = "587"
        try:
            channel.send(SAMPLE_CONTENT, meta={"date": "2026-05-08"})
            mock_server.sendmail.assert_called_once()
        finally:
            os.environ.pop("SMTP_HOST", None)
            os.environ.pop("SMTP_PORT", None)
