"""
Inter-agent report (CR) system.

Each significant exchange produces a dated Markdown file in reports/.
Agents can read CRs from their peers (defined in their .md).
Deleting a CR = rollback to previous context.
"""

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

REPORTS_DIR = Path("reports")


def ensure_reports_dir():
    REPORTS_DIR.mkdir(exist_ok=True)


def generate_report_filename(agent_name: str) -> str:
    """Generate a timestamped filename: {agent}_{YYYYMMDD}_{HHMMSS}.md"""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{agent_name}_{ts}.md"


def save_report(
    agent_name: str,
    summary: str = "",
    exchanges: list[dict] | None = None,
    actions: list[str] | None = None,
    files_generated: list[str] | None = None,
    # New params for LLM-based summary generation
    history: list[dict] | None = None,
    client=None,
    model: str = "",
    summary_prompt: str = "",
) -> str:
    """
    Save a CR markdown file.

    Supports two calling conventions:
      1. Legacy:  save_report(agent_name, summary, exchanges, actions, files_generated)
      2. New:     save_report(agent_name, history=..., client=..., model=..., summary_prompt=...)
                  -> generates summary via LLM, uses history as exchanges.

    Args:
        agent_name: Name of the agent
        summary: Pre-generated summary (legacy mode)
        exchanges: List of {role, content} (legacy mode)
        actions: List of actions taken
        files_generated: List of output files produced
        history: Conversation history (new mode — used as exchanges)
        client: ResilientClient instance (new mode — for LLM summary)
        model: Model ID (new mode — for LLM summary)
        summary_prompt: System prompt for summary generation (new mode)

    Returns:
        Path to the saved report.
    """
    ensure_reports_dir()

    # New calling convention: generate summary via LLM from history
    if history is not None:
        exchanges = history
        if client and model and summary_prompt and len(history) > 0:
            try:
                condensed = []
                for msg in history[-20:]:
                    role = "User" if msg["role"] == "user" else "Agent"
                    content = msg["content"][:300]
                    condensed.append(f"{role}: {content}")
                context = "\n".join(condensed)
                summary = client.chat(
                    messages=[
                        {"role": "system", "content": summary_prompt},
                        {"role": "user", "content": f"Session exchanges:\n{context}"},
                    ],
                    model=model,
                    temperature=0.3,
                    max_tokens=500,
                )
            except Exception as e:
                logger.warning(f"LLM summary generation failed, using fallback: {e}")
                summary = f"Session with {len(history)} exchanges. Summary generation failed."
        elif not summary:
            summary = f"Session with {len(history)} exchanges."

    exchanges = exchanges or []
    actions = actions or []
    files_generated = files_generated or []

    filename = generate_report_filename(agent_name)
    filepath = REPORTS_DIR / filename

    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# Report -- {agent_name}",
        f"",
        f"**Date**: {date_str}",
        f"**Agent**: {agent_name}",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        summary,
        f"",
    ]

    if actions:
        lines.append("## Actions taken")
        lines.append("")
        for action in actions:
            lines.append(f"- {action}")
        lines.append("")

    if files_generated:
        lines.append("## Generated files")
        lines.append("")
        for f in files_generated:
            lines.append(f"- `{f}`")
        lines.append("")

    # Append a condensed conversation log
    lines.append("## Exchanges (condensed)")
    lines.append("")
    for msg in exchanges:
        role = "**User**" if msg["role"] == "user" else f"**{agent_name}**"
        content = msg["content"]
        if len(content) > 500:
            content = content[:500] + " [...]"
        # Remove code blocks for readability in summary
        content_clean = re.sub(r"```[\s\S]*?```", "[code block]", content)
        lines.append(f"{role}: {content_clean}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Automatically generated by Heliograph -- {date_str}*")

    filepath.write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Report saved: {filepath}")
    return str(filepath)


def load_peer_reports(
    peer_agents: list[str],
    max_reports_per_peer: int = 3,
    max_chars_per_report: int = 2000,
) -> str:
    """
    Load recent reports from peer agents.

    Args:
        peer_agents: List of agent names whose reports to load
        max_reports_per_peer: Max number of recent reports per peer
        max_chars_per_report: Truncate each report to this length

    Returns:
        Formatted string with peer reports to inject into context.
    """
    if not REPORTS_DIR.exists():
        return ""

    sections = []

    for peer in peer_agents:
        pattern = f"{peer}_*.md"
        reports = sorted(REPORTS_DIR.glob(pattern), reverse=True)
        reports = reports[:max_reports_per_peer]

        if not reports:
            continue

        sections.append(f"### Reports from agent '{peer}' (most recent)")
        for report_path in reports:
            content = report_path.read_text(encoding="utf-8", errors="replace")
            if len(content) > max_chars_per_report:
                content = content[:max_chars_per_report] + "\n[... truncated]"
            sections.append(f"\n--- [{report_path.name}] ---\n{content}")

    if not sections:
        return ""

    return (
        "## Reports from linked agents\n"
        "These reports summarize recent exchanges with other agents. "
        "Use them as context to understand project progress.\n\n"
        + "\n\n".join(sections)
    )


def list_reports(agent_name: Optional[str] = None) -> list[dict]:
    """
    List all reports, optionally filtered by agent.
    Returns list of {filename, agent, date, path}.
    """
    if not REPORTS_DIR.exists():
        return []

    pattern = f"{agent_name}_*.md" if agent_name else "*.md"
    reports = []

    for path in sorted(REPORTS_DIR.glob(pattern), reverse=True):
        name = path.stem
        parts = name.rsplit("_", 2)
        if len(parts) >= 3:
            agent = parts[0]
            try:
                date = datetime.strptime(f"{parts[1]}_{parts[2]}", "%Y%m%d_%H%M%S")
                date_str = date.strftime("%Y-%m-%d %H:%M")
            except ValueError:
                date_str = "?"
                agent = name
        else:
            agent = name
            date_str = "?"

        reports.append({
            "filename": path.name,
            "agent": agent,
            "date": date_str,
            "path": str(path),
        })

    return reports


def delete_last_report(agent_name: Optional[str] = None) -> Optional[str]:
    """
    Delete the most recent report (optionally for a specific agent).
    Returns the filename of the deleted report, or None.
    """
    reports = list_reports(agent_name)
    if not reports:
        return None

    path = Path(reports[0]["path"])
    filename = path.name
    path.unlink()
    logger.info(f"Deleted report: {filename}")
    return filename